"""empty message

Revision ID: 44e03d379809
Revises: 6f2c651f24b5
Create Date: 2026-07-13 13:53:42.430449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '44e03d379809'
down_revision: Union[str, Sequence[str], None] = '6f2c651f24b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribuguide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('biografia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tribuguide')
    # ### end Alembic commands ###
