"""empty message

Revision ID: ddaccb5a1ef0
Revises: 44e03d379809
Create Date: 2026-08-31 12:00:41.631179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ddaccb5a1ef0'
down_revision: Union[str, Sequence[str], None] = '44e03d379809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tribu_payment_methods')
    op.drop_table('tribu_orders')
    with op.batch_alter_table('tribu_admin_users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_constraint(batch_op.f('tribu_admin_users_email_key'), type_='unique')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tribu_carts', schema=None) as batch_op:
        batch_op.alter_column('items_json',
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_constraint(batch_op.f('unique_user_cart'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tribu_carts_user_id'), ['user_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('tribu_carts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tribu_client_notes', schema=None) as batch_op:
        batch_op.alter_column('etiqueta',
               nullable=False,
               existing_server_default=sa.text("'NUEVO'::character varying"))
        batch_op.drop_constraint(batch_op.f('tribu_client_notes_whatsapp_cliente_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tribu_client_notes_whatsapp_cliente'), ['whatsapp_cliente'], unique=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tribu_coupons', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               nullable=False,
               existing_server_default=sa.text("'PORCENTAJE'::character varying"))
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('usos_maximos',
               nullable=False,
               existing_server_default=sa.text('100'))
        batch_op.alter_column('usos_actuales',
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint(batch_op.f('tribu_coupons_codigo_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tribu_coupons_codigo'), ['codigo'], unique=True)

    with op.batch_alter_table('tribu_gift_cards', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               nullable=False,
               existing_server_default=sa.text("'EXPERIENCIA'::character varying"))
        batch_op.alter_column('estado',
               nullable=False,
               existing_server_default=sa.text("'PENDIENTE_PAGO'::character varying"))
        batch_op.drop_constraint(batch_op.f('tribu_gift_cards_codigo_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tribu_gift_cards_codigo'), ['codigo'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('fecha_expiracion')

    with op.batch_alter_table('tribu_notifications', schema=None) as batch_op:
        batch_op.alter_column('es_admin',
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('es_publico',
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('target_url',
               nullable=False,
               existing_server_default=sa.text("'/'::character varying"))
        batch_op.alter_column('leido',
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tribu_services', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tribu_session_reservations', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               nullable=False)
        batch_op.alter_column('porcentaje_pago',
               nullable=False,
               existing_server_default=sa.text('100.0'))
        batch_op.alter_column('monto_pagado',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('monto_pendiente',
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.drop_constraint(batch_op.f('tribu_session_reservations_session_id_fkey'), type_='foreignkey')
        batch_op.drop_column('fecha_reserva')

    with op.batch_alter_table('tribu_sessions', schema=None) as batch_op:
        batch_op.alter_column('requiere_correo_obligatorio',
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('requiere_porcentaje_obligatorio',
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_constraint(batch_op.f('tribu_sessions_checkin_token_key'), type_='unique')

    with op.batch_alter_table('tribu_users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('idx_tribu_users_email'))
        batch_op.drop_constraint(batch_op.f('tribu_users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tribu_users_email'), ['email'], unique=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tribu_workshops', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               nullable=False,
               existing_server_default=sa.text("'TALLER'::character varying"))
        batch_op.alter_column('moneda',
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
        batch_op.alter_column('is_active',
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tribuguide', schema=None) as batch_op:
        batch_op.alter_column('biografia',
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tribuguide', schema=None) as batch_op:
        batch_op.alter_column('biografia',
               nullable=True)

    with op.batch_alter_table('tribu_workshops', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('moneda',
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
        batch_op.alter_column('tipo',
               nullable=True,
               existing_server_default=sa.text("'TALLER'::character varying"))

    with op.batch_alter_table('tribu_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tribu_users_email'))
        batch_op.create_unique_constraint(batch_op.f('tribu_users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_tribu_users_email'), ['email'], unique=False)
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tribu_sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('tribu_sessions_checkin_token_key'), ['checkin_token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('requiere_porcentaje_obligatorio',
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('requiere_correo_obligatorio',
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('tribu_session_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reserva', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tribu_session_reservations_session_id_fkey'), 'tribu_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('monto_pendiente',
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('monto_pagado',
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('porcentaje_pago',
               nullable=True,
               existing_server_default=sa.text('100.0'))
        batch_op.alter_column('session_id',
               nullable=True)

    with op.batch_alter_table('tribu_services', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tribu_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.alter_column('leido',
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('target_url',
               nullable=True,
               existing_server_default=sa.text("'/'::character varying"))
        batch_op.alter_column('es_publico',
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('es_admin',
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('tribu_gift_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_expiracion', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tribu_gift_cards_codigo'))
        batch_op.create_unique_constraint(batch_op.f('tribu_gift_cards_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('estado',
               nullable=True,
               existing_server_default=sa.text("'PENDIENTE_PAGO'::character varying"))
        batch_op.alter_column('tipo',
               nullable=True,
               existing_server_default=sa.text("'EXPERIENCIA'::character varying"))

    with op.batch_alter_table('tribu_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tribu_coupons_codigo'))
        batch_op.create_unique_constraint(batch_op.f('tribu_coupons_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('usos_actuales',
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('usos_maximos',
               nullable=True,
               existing_server_default=sa.text('100'))
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('tipo',
               nullable=True,
               existing_server_default=sa.text("'PORCENTAJE'::character varying"))

    with op.batch_alter_table('tribu_client_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tribu_client_notes_whatsapp_cliente'))
        batch_op.create_unique_constraint(batch_op.f('tribu_client_notes_whatsapp_cliente_key'), ['whatsapp_cliente'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('etiqueta',
               nullable=True,
               existing_server_default=sa.text("'NUEVO'::character varying"))

    with op.batch_alter_table('tribu_carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tribu_carts_user_id_fkey'), 'tribu_users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_tribu_carts_user_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_user_cart'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('items_json',
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('tribu_admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('tribu_admin_users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_active',
               nullable=True,
               existing_server_default=sa.text('true'))

    op.create_table('tribu_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('cliente_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cliente_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cliente_apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cliente_telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cliente_pais', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cliente_direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cliente_ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cliente_codigo_postal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('numero_referencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('comprobante_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monto_subtotal', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('monto_descuento', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('monto_total', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'PENDING_VERIFICATION'::character varying"), autoincrement=False, nullable=True),
    sa.Column('aliado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comision_plataforma', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cupon_codigo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tribu_users.id'], name=op.f('tribu_orders_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('tribu_orders_pkey'))
    )
    op.create_table('tribu_payment_methods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aliado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icono', sa.VARCHAR(length=50), server_default=sa.text("'credit-card'::character varying"), autoincrement=False, nullable=True),
    sa.Column('detalles_texto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tribu_payment_methods_pkey'))
    )
    # ### end Alembic commands ###
